# Docker compose script that demonstrates the DALiuGE-based PBC
#
# ICRAR - International Centre for Radio Astronomy Research
# (c) UWA - The University of Western Australia, 2019
# Copyright by UWA (in the framework of the ICRAR)
# All rights reserved
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2.1 of the License, or (at your option) any later version.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston,
# MA 02111-1307  USA
#
version: '3.6'

services:

  config_database:
    image: redis:5.0.1-alpine
    ports:
      - 6379:6379

  nm:
    image: nexus.engageska-portugal.pt/ska-docker/yanda-daliuge
    command: ["dlg", "nm", "-v", "-H", "0.0.0.0"]

  dim:
    image: nexus.engageska-portugal.pt/ska-docker/yanda-daliuge
    command: ["dlg", "dim", "-N", "nm", "-v", "-H", "0.0.0.0"]
    depends_on:
    - nm

  processing_controller:
    image: skasip/processing_controller:latest
    environment:
    - CELERY_BROKER_URL=redis://config_database/1
    - CELERY_RESULT_BACKEND=redis://config_database/2
    - REDIS_HOST=config_database
    - USE_DLG=1
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
    - config_database

  dlg_pcb:
    image: icrar/daliuge_pbc:latest
    environment:
    - CELERY_BROKER_URL=redis://config_database/1
    - CELERY_RESULT_BACKEND=redis://config_database/2
    - REDIS_HOST=config_database
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
    - config_database
    - dim
